# Generated by Django 4.1.7 on 2023-02-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveBigIntegerField(default=0, verbose_name='Количество')),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='uploads/img/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('os', models.CharField(blank=True, max_length=255, verbose_name='Операционная система')),
                ('display', models.CharField(blank=True, max_length=255, verbose_name='Экран')),
                ('camera', models.CharField(blank=True, max_length=255, verbose_name='Камера')),
                ('memory', models.CharField(blank=True, max_length=255, verbose_name='Память')),
                ('battery', models.CharField(blank=True, max_length=255, verbose_name='Аккумулятор')),
                ('cpu', models.CharField(blank=True, max_length=255, verbose_name='Процессор')),
                ('sim', models.CharField(blank=True, max_length=255, verbose_name='SIM-карты')),
                ('communication', models.CharField(blank=True, max_length=255, verbose_name='Стандарты связи')),
                ('weight', models.CharField(blank=True, max_length=255, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='uploads/img/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('os', models.CharField(blank=True, max_length=255, verbose_name='Операционная система')),
                ('display', models.CharField(blank=True, max_length=255, verbose_name='Экран')),
                ('graphic', models.CharField(blank=True, max_length=255, verbose_name='Видеокарта')),
                ('memory', models.CharField(blank=True, max_length=255, verbose_name='Память')),
                ('battery', models.CharField(blank=True, max_length=255, verbose_name='Аккумулятор')),
                ('cpu', models.CharField(blank=True, max_length=255, verbose_name='Процессор')),
                ('weight', models.CharField(blank=True, max_length=255, verbose_name='SIM-карты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='main.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='onwer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.cartproduct'),
        ),
    ]
