# Generated by Django 4.1.7 on 2023-03-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_for_anonymous_user_cart_in_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='onwer',
            new_name='owner',
        ),
    ]
